# Numpy Introduction

Biblioteca de Algebra Linear para Python

Métodos são construidos em C, tornando a biblioteca muito rápida (bloco de construção para outras libs).

Arrays: principal ferramenta da biblioteca. Podem ser 1d (vetores) ou 2d (matrizes).

Extremamente útil (otimizado) para tratamento de big data / data science

* Topicos:
    * Importar biblioteca
    * Tempo de Processamento
    * lookfor: Procurar Funções/Metodos Proprietarios/Nativos 
    * Inicializações de Arrays

In [1]:
# Importando a biblioteca

import numpy as np

# Tempo de processamento: Arrays x listas

array1 = list(range(1000000))
%time for _ in range(10):array1 * 2

array2 = np.arange(1000000)
%time for _ in range(10):array2 * 2


Wall time: 172 ms
Wall time: 15.7 ms


In [2]:
# lookfor: "similar ao help do matlab"

np.lookfor('accumulate')

Search results for 'accumulate'
-------------------------------
numpy.ufunc.accumulate
    Accumulate the result of applying the operator to all elements.
numpy.ufunc.at
    Performs unbuffered in place operation on operand 'a' for elements
numpy.ufunc.reduceat
    Performs a (local) reduce with specified slices over a single axis.


In [3]:
# Inicializando array: lista 1d (vetor)

lista1 = [1,2,3]
array1 = np.array(lista1)
display(array1)

# Inicializando array: lista 2d (matriz)

lista2 = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(lista2)
display(array2)

# Inicializando array: arange (inicial, final, passo)

array3 = np.arange(0,10)    # De 0 a 9 (ultimo # descartado). passo = 1.
display(array3)

array4 = np.arange(0,11,2)  # De 0 a 10 (ultimo # descartado). passo = 2.
display(array4)

# Inicializando array: zeros (apenas valores 0)

array5 = np.zeros(3)        # Array de dimensão [1x3]
display(array5)

array6 = np.zeros((5,5))    # Array de dimensão [5x5]
display(array6)

# Inicializando array: ones (apenas valores 1)

array7 = np.ones((3,3))     # Matrix de "uns" [3x3]
display(array7)

# Inicializando array: eye (matriz identidade)

array8 = np.eye(4)          # Matrix [4x4]
display(array8)

array([1, 2, 3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10])

array([ 0.,  0.,  0.])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [4]:
# Inicializando array: linspace(start,end,num_of_samples)

array9 = np.linspace(0,10,3)
display(array9)

# Inicializando array: logspace(start,end,num_of_samples,base_log)

array10 = np.logspace(2.0, 3.0, num = 5, base = 11)
display(array10)

# Obs: Configurar a "semente" dos números aleatórios (para garantir mesma sequência)

np.random.seed(101)

# Inicializando array: números aleatórios com distribuição uniforme.

array11 = np.random.rand(5)      # 5 valores entre 0 e 1
print(array11)

array12 = np.random.rand(5)*100  # 5 valores entre 0 e 100 
print(array12)

array13 = np.random.rand(5,4)    # 20 valores entre 0 e 1 (não precisa passar tupla)
print(array13)

# Inicializando array: números aleatórios com distribuição gaussiana.

array14 = np.random.randn(4)    # 4 valores, média = 0, desvio padrão = 1
print(array14)

# Inicializando array: números aleatórios com distribuição uniforme.

array15 = np.random.randint(0,100)    # de 0 a 99, 1 num
print(array15)

array16 = np.random.randint(0,100,10) # de 0 a 99, 10 num
print(array16)

array([  0.,   5.,  10.])

array([  121.        ,   220.36039471,   401.31159963,   730.8527479 ,
        1331.        ])

[ 0.51639863  0.57066759  0.02847423  0.17152166  0.68527698]
[ 83.38968626  30.69662197  89.36130797  72.15438618  18.99389542]
[[ 0.55422759  0.35213195  0.1818924   0.78560176]
 [ 0.96548322  0.23235366  0.08356143  0.60354842]
 [ 0.72899276  0.27623883  0.68530633  0.51786747]
 [ 0.04848454  0.13786924  0.18696743  0.9943179 ]
 [ 0.5206654   0.57878954  0.73481906  0.54196177]]
[-1.70608593 -1.15911942 -0.13484072  0.39052784]
12
[17 75 79 97 93 24 36 63 19 35]
