# Numpy Array Manipulation

* Topicos:
    * Atributos (shape, dtype, ndim)
    * Modificar Formato (reshape)
    * Inserir e Deletar Valores (insert(), append(), delete())
    * Modificar / Estabelecer tipo de dados (astype)
    * DateTime

In [36]:
# Importar Library

import numpy as np

# Criar array

array1 = np.arange(1,10) # Array 1d de 9 elementos [1 - 9]
print(array1)

# Atributos do Array (shape, dtype, ndim)

print(array1.shape)     # valor das dimensões
print(array1.dtype)     # tipos de dados
print(array1.ndim)      # numero de dimensoes

# Modificar Formato (reshape)

array2 = array1.reshape((3,3))
print(array2, array2.shape, array2.ndim)

array3 = array1.reshape(1,9)
print(array3,array3.shape)

array4 = array1.reshape(9,1)
print(array4,array4.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
int32
1
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2
[[1 2 3 4 5 6 7 8 9]] (1, 9)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] (9, 1)


In [37]:
# Inserir e Deletar Valores da Array

# cria array

array1 = np.array([10,20,30])
print(array1)

# insere valores no array

array1 = np.insert(array1,1,15) # insere, na posição 1, valor 15
print(array1)

array1 = np.insert(array1,0,5)  # insere, na posição 0, valor 5, 
print(array1)

array1 = np.append(array1,40)   # insere, na ultima posição, valor 40
print(array1)

# deleta valor do array

array1 = np.delete(array1,0)    # deleta, do array1, valor da posição 0
print(array1)

[10 20 30]
[10 15 20 30]
[ 5 10 15 20 30]
[ 5 10 15 20 30 40]
[10 15 20 30 40]


In [35]:
# Modificar / Estabelecer tipo de dados da array

array4 = np.array([1,2,3], dtype = np.int32)
array5 = array4.astype(np.float64)
print(array4.dtype)
print(array5.dtype)

array6 = np.array([3.7,5.5,-2.6])
array7 = array6.astype(np.int32)
print(array6)
print(array7)

array_str1 = np.array(['1.25','2.5','3.7'],dtype=np.string_)
array_str2 = array_str1.astype(float)
print(array_str1)
print(array_str2)

int32
float64
[ 3.7  5.5 -2.6]
[ 3  5 -2]
[b'1.25' b'2.5' b'3.7']
[ 1.25  2.5   3.7 ]


In [38]:
# DateTime

# Link: https://pt.wikipedia.org/wiki/ISO_8601

# Criar dados

x = np.datetime64('2017-05-01')
y = np.datetime64('2017-10')
print(x.dtype)
print(y.dtype)

# Manipulação de datas

z = np.arange('2017-01','2017-12',dtype='datetime64[M]')
print(z)
a = np.datetime64('2017') + np.timedelta64(10,'M')
print(a)
b = np.timedelta64(1,'W') / np.timedelta64(1,'D')
print(b)

datetime64[D]
datetime64[M]
['2017-01' '2017-02' '2017-03' '2017-04' '2017-05' '2017-06' '2017-07'
 '2017-08' '2017-09' '2017-10' '2017-11']
2017-11
7.0
