# SciPi Library

Coleção de algoritmos matemáticos e funções construídas sob Numpy

Fornece comandos e classes de alto nível para manipular e visualizar dados

Rivaliza com sistemas como MATLAB, IDL, Octave, R-Lab e SciLab.

Programação paralela, base de dados e sub-rotinas de base de dados...

Transformadas de Fourier, Funções de Bessel...

In [3]:
# Import Library

import numpy as np

# Create 2d Array (Matrix)

A = np.array([[1,2,3],[4,5,6],[7,8,8]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 8]]


In [14]:
# Linar Algebra Functions

from scipy import linalg

# Determinant

print(linalg.det(A))
print()

# LU Decomposition
# A = P L U
# P (permutation matrix), L (lower triangular matrix, with ones in diagonal), U (upper triangular matrix)

P, L, U = linalg.lu(A)
print(P)
print(L)
print(U)

B = np.dot(P,L)
B = np.dot(B,U)
print(B)
print()

# Eigenvalues and Eigenvectors

eigVal, eigVec = linalg.eig(A)

print(eigVal)
print(eigVec)
print()

# Linear Systems Solutions A.x = v

v = np.array([[2],[3],[5]])
x = linalg.solve(A,v)
print(x)
print(np.dot(A,x))


2.999999999999997

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]
[[ 1.          0.          0.        ]
 [ 0.14285714  1.          0.        ]
 [ 0.57142857  0.5         1.        ]]
[[ 7.          8.          8.        ]
 [ 0.          0.85714286  1.85714286]
 [ 0.          0.          0.5       ]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  8.]]

[ 15.55528261+0.j  -1.41940876+0.j  -0.13587385+0.j]
[[-0.24043423 -0.67468642  0.51853459]
 [-0.54694322 -0.23391616 -0.78895962]
 [-0.80190056  0.70005819  0.32964312]]

[[-2.33333333]
 [ 3.66666667]
 [-1.        ]]
[[ 2.]
 [ 3.]
 [ 5.]]


In [20]:
# Sparse Linear Algebra

from scipy import sparse

A = sparse.lil_matrix((1000, 1000))

In [21]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [22]:
A[0,:100] = np.random.rand(100)

A[1,100:200] = A[0,:100]

A.setdiag(np.random.rand(1000))

In [23]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

In [24]:
# Convert matrix to compressed sparse row

A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [27]:
# Solve linear Systems

from scipy.sparse import linalg

b = np.random.rand(1000)

x = linalg.spsolve(A, b)

print(x)

[  2.32541647e+04  -4.89736324e+02   1.43331484e+00   7.01836033e+00
   1.61488831e+00   4.38787457e+00   1.04454465e+00   1.99186651e+01
   4.37574196e-01   3.57273354e-01   7.38487803e-01   1.10067183e+00
   4.28550108e-01   4.01502959e-01   1.28275853e+00   8.30321435e-01
   8.02942289e-01   3.03043345e-01   7.08753017e-01   1.25664388e+00
   1.78541752e+00   2.14273678e-01   1.11884525e+00   4.61124768e+01
   6.97744268e-01   3.04496968e+00   7.86019573e-01   4.27015091e-01
   6.68173103e-01   8.06147382e-02   8.88279076e-01   5.56346906e+00
   5.33280982e-01   6.63458344e-02   2.55904600e+00   2.40292494e+00
   1.27175856e+00   3.39744546e+00   1.40287296e+00   3.85484030e+00
   9.77838214e-01   6.66122741e-01   8.40912437e-01   5.59271351e-01
   5.09289228e-01   1.48873101e+00   1.24063779e+00   9.70007369e+00
   1.48956156e+00   2.64448570e+01   5.13883076e-01   5.04628593e+00
   2.77488973e+00   1.72807715e-01   8.93713565e-01   1.13172473e+01
   5.71141064e+00   1.26862141e+01

C:\Users\david\Anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:102: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  SparseEfficiencyWarning)
