# Numpy Array Operations

* Topicos:
    * Operações Aritméticas
    * Operações Ponto a ponto
    * Metodos da Biblioteca (funções Universais)
    * Produto Interno e Externo
    * Matriz Inversa e Transposta

In [20]:
# Importar Library

import numpy as np

# Criar array

array1 = np.arange(1,10) # Array 1d de 9 elementos [1 - 9]
array2 = array2 = array1.reshape((3,3))

# Operações Aritmeticas (por escalar)

array3 = array2 + 2
print(array3)

array3 = array2 - 2
print(array3)

array3 = array2 * 2
print(array3)

array3 = array2 / 2
print(array3)

array3 = array2 ** 2
print(array3)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 0.5  1.   1.5]
 [ 2.   2.5  3. ]
 [ 3.5  4.   4.5]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [21]:
# Operações Aritmeticas (ponto a ponto)

array3 = array2 + array2
print(array3)

array3 = array2 - array2
print(array3)

array3 = array2 * array2
print(array3)

array3 = array2 / array2
print(array3)

array4 = 2*np.ones((3,3))

array3 = array2 ** array4
print(array3)

# Obs1: Operações "inválidas" (0 / 0), geram o valor "nan"
# Obs2: Divisão por 0, gera valor "inf"

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[  1.   4.   9.]
 [ 16.  25.  36.]
 [ 49.  64.  81.]]


In [22]:
# Metodos Nativos da Biblioteca (Funções Universais)

# Link: https://docs.scipy.org/doc/numpy/reference/ufuncs.html

array1 = np.arange(1,6)
print(array1)

print(array1.max(),np.max(array1))
print(array1.argmax())

print(array1.min(),np.min(array1))
print(array1.argmin())

print(np.sqrt(array1))
print(np.square(array1))

print(np.exp(array1))
print(np.log(array1))

print(np.mean(array1))
print(np.std(array1))

print(np.sin(array1))


[1 2 3 4 5]
5 5
4
1 1
0
[ 1.          1.41421356  1.73205081  2.          2.23606798]
[ 1  4  9 16 25]
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591 ]
[ 0.          0.69314718  1.09861229  1.38629436  1.60943791]
3.0
1.41421356237
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [23]:
# Metodos Nativos da Biblioteca (Funções Universais) 

x = np.arange(5,10)
print(x)

y = np.ones([5,5])*10
print(y)

z = np.repeat(x,3).reshape(5,3)
print(z)

# Funcoes
print(np.mod(y,x))            # Resto da divisao
print(np.minimum(x,7))        # Compara valor a valor com o 7
print(np.median(z))           # Mediana de todos os valores
print(np.median(z,axis=0))    # Mediana por coluna (das linhas)
print(np.median(z,axis=1))    # Mediana por linha (das colunas)
print(np.add.accumulate(x))   # soma acumulada
print(np.multiply.outer(x,x)) # Multiplicação matricial


[5 6 7 8 9]
[[ 10.  10.  10.  10.  10.]
 [ 10.  10.  10.  10.  10.]
 [ 10.  10.  10.  10.  10.]
 [ 10.  10.  10.  10.  10.]
 [ 10.  10.  10.  10.  10.]]
[[5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]
[[ 0.  4.  3.  2.  1.]
 [ 0.  4.  3.  2.  1.]
 [ 0.  4.  3.  2.  1.]
 [ 0.  4.  3.  2.  1.]
 [ 0.  4.  3.  2.  1.]]
[5 6 7 7 7]
7.0
[ 7.  7.  7.]
[ 5.  6.  7.  8.  9.]
[ 5 11 18 26 35]
[[25 30 35 40 45]
 [30 36 42 48 54]
 [35 42 49 56 63]
 [40 48 56 64 72]
 [45 54 63 72 81]]


In [38]:
# Inverse and Transpose

import numpy as np
from numpy.linalg import inv
from numpy.linalg import pinv

# Produto escalar:  np.inner() (vectors) / np.dot() (matrices)
# Produto vetorial: np.outer()

# Inner product of 1D arrays

B = np.array([1,2,3])
C = np.array([4,5,6])
A = np.inner(B,C)

print(A)

# Transpose of 1D vectors

A = np.array([[1,2,3]]) # create as a 2D object
B = A.T
C = A.transpose()

print(B)
print(C)

# Matrix Class

m = np.matrix([[2,3],[4,5]]) # create matrix object
print(m)

m_inv = m.I                  # calculate matrix inverse
print(m_inv)

print(np.matmul(m,m_inv))    # Identity Matrix

# Transpose and inverse Using Arrays (A = B' * inv(C))
B = np.random.randn(2,2)
C = np.random.randn(2,2)
A = np.dot(B.T, inv(C))
A = np.matmul(B.T, inv(C))

# Transpose and inverse using Matrices (A = B' * inv(C))
B = np.mat(B) # cast B from array object to matrix object
C = np.mat(C) # cast C from array object to matrix object
A = B.T*C.I

32
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[2 3]
 [4 5]]
[[-2.5  1.5]
 [ 2.  -1. ]]
[[ 1.  0.]
 [ 0.  1.]]
